services:
  app:
    build: .
    ports:
      - "3000:3000"

  tipping_db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tipping
      POSTGRES_DB: tipping
    volumes:
      - ./postgres/data:/var/lib/postgresql/data